### ISSUE TITLE
1.5.0

### ISSUE THREAD

**Issue by luciorubeens** [Tids/arkclient_pkg#1]
Hey Fabian, thank you for your collaboration! I used your repo to update the version, I just removed the exchanges entries. @boldninja please include him in the github bounty.

**Comment by Tids** [comment]
Hi @luciorubeens. I'm glad you where able to get it.
I just have to ask, what that github bounty is? I'm really not familiar with github/git at all 😂

**Comment by luciorubeens** [comment]
Take a look: [ARK Github Development Bounty Program](https://blog.ark.io/ark-github-development-bounty-113806ae9ffe)

**Comment by boldninja** [comment]
@Tids Can you provide me with your ARK address so I can distribute you your bounty?

**Comment by Tids** [comment]
@boldninja AaUGPfpzXRJgVrxCGYtDw6brUVzZTeMm3p <- this one?
